### ISSUE TITLE
unsupported mode '2' for pin '15' at ../lib/Device/Firmata/Platform.pm line 823.

### ISSUE THREAD

**Issue by bcarroll** [ntruchsess/perl-firmata#14]
examples/test.pl is producing an error "unsupported mode '2' for pin '15' at ../lib/Device/Firmata/Platform.pm line 823." 

This test was done using an Arduino Mega 2560 R3 and the StandardFirmata sketch included with Arduino 1.0.5.

I did not get this error with an Arduino Nano v3.

I read something a while ago about changing a delay to support the Mega, but I thought that had been included in the newer versions of the StandardFirmata sketch.

**Comment by jnsbyr** [comment]
duplicate of #15
