### ISSUE TITLE
Capability query does not respect protocol version

### ISSUE THREAD

**Issue by git-developer** [ntruchsess/perl-firmata#30]
I'm using perl-firmata to read digital inputs and 433 MHz RC signals in FHEM (perl-firmata 0.64). The firmata implementation is [RCSwitchFirmata 2.6](https://github.com/git-developer/RCSwitchFirmata/tree/1a79edc97485e3c7d8227ebccdb9acea9755d1dd/arduino/libraries/Firmata) based on ConfigurableFirmata 2.6.

- ConfigurableFirmata 2.6 [does not have a feature](https://github.com/firmata/ConfigurableFirmata/blob/17cfffe92985317852bf0564ef550b858f574fdc/src/ConfigurableFirmata.h) with ID `0x0B`.
- RCSwitchFirmata 2.6 [uses](https://github.com/git-developer/RCSwitchFirmata/blob/1a79edc97485e3c7d8227ebccdb9acea9755d1dd/arduino/libraries/Firmata/utility/RCInputFirmata.cpp#L22) Feature-ID `0x0B` for Feature _RC_RECEIVE_.
- ConfigurableFirmata 2.7 and higher [use](https://github.com/firmata/ConfigurableFirmata/blob/ade6a007d0938fd2dc60830883890477a7a573e5/src/ConfigurableFirmata.h#L88) Feature-ID `0x0B` for Feature _PIN_MODE_PULLUP_.

perl-firmata seems to be sensitive for the firmata protocol version (e.g. in [Constants.pm](https://github.com/ntruchsess/perl-firmata/blob/f41b68101cdbadd177441ac763f825b9b0a5be30/lib/Device/Firmata/Constants.pm#L43])). Unfortunately, `$MODENAMES` in [Protocol.pm](https://github.com/ntruchsess/perl-firmata/blob/f41b68101cdbadd177441ac763f825b9b0a5be30/lib/Device/Firmata/Protocol.pm#L105) is defined globally and does not respect the firmata protocol version.

Thus, _RC_RECEIVE_ pins are reported as _PIN_MODE_PULLUP_ pins. The application tries to configure the pullup features, which fails.

I therefore request to make `Protocol.pm` version-dependent.

**Comment by jnsbyr** [comment]
>
> @git-developer
From the commit logs you will see that the pullup support was introduced in
version 0.64 so you might chechout a 0.63 version to see if it makes a
difference for your application.

In the same commit logs you will find that the pullup support is a Firmata
Protocol 2.5 feature (see commit log of version 2.5.0 at
https://github.com/firmata/arduino/releases). The version number of
ConfigurableFirmata has nothing to do with the implemented protocol version
- but the protocol version is the only version important for perl-firmata!
There is no "if ConfigurableFirmata version X.Y code anywhere" and such an
approach should be avoided anyway. If a Firmata release claims to implement
Firmata Protocol version 2.5 or higher it should provide the pullup
feature.

If I remember correctly there is no fallback in perl-firmata 0.64 to the
"old" workaround for the pullup support if feature 0x0B is not implemented.
This would resolve your issue but downgrading perl-firmata or upgrading
ConfigurableFirmata should be the preferred solutions, so please post your
test results with the previous perl-firmata version.

**Comment by git-developer** [comment]
OK, I see. ConfigurableFirmata 2.6 (and thus the derived RCSwitchFirmata 2.6) [claims to support](https://github.com/firmata/ConfigurableFirmata/blob/17cfffe92985317852bf0564ef550b858f574fdc/src/ConfigurableFirmata.h#L22) protocol version 2.6.2 although it does not support the pullup feature introduced in version 2.5.0. I didn't realize this.

> there is no fallback in perl-firmata 0.64 to the "old" workaround for the pullup support

That's not a big deal because fortunately [you implemented](https://svn.fhem.de/trac/browser/trunk/fhem/FHEM/20_FRM_IN.pm?rev=16012#L105) this backwards-compatibility on top of perl-firmata in my application (FHEM). Thanks for that. It just doesn't work because of the broken firmata implementation.

I will not downgrade to perl-firmata 0.63 because FHEM is distributed with version 0.64 and I don't want to fiddle with it. I will instead manually disable pullup support in the [FHEM source code](https://svn.fhem.de/trac/browser/trunk/fhem/FHEM/20_FRM_IN.pm?rev=16012#L88) as a quick fix and later upgrade my firmata firmware implementation.

**Comment by jnsbyr** [comment]
Thanks for your feedback. I am glad you have found a quick fix on the
application level.

Still it intrigues me why this problem occurs. It is not easy for me right
now to do an in depth analysis. What I was able to find out so far gives me
the impression that the pullup support is completely based on the capabiliy
response of the Firmata device and not fixed to any specific Firmata
protocol version. In FHEM the input pin should be listed under
"pullup_pins" if the devices claims to support this feature. But how can
this happen if ConfigurableFirmata 2.6 does not list support for pin mode
0x0B in ConfigurableFirmata.h?

Even though you have already closed this issue I will try to find out if
the cause is related to perl-firmata, ConfigurableFirmata or the FHEM
Firmata module.

**Comment by git-developer** [comment]
> But how can this happen if ConfigurableFirmata 2.6 does not list support for pin mode 0x0B in ConfigurableFirmata.h?

The problem would not happen with pure ConfigurableFirmata; I'm using RCSwitchFirmata, an extension of ConfigurableFirmata which offers a Feature _RC_RECEIVE_ with ID `0x0B`. This feature is supported for all interrupt-enabled pins, thus the request for `0x0B` returns 6 pins on an Arduino Mega (with 6 interrupt pins). perl-firmata then tries to configure these as pullup pins, which fails.
